---
- name: Enable EPEL (Extra Packages for Enterprise Linux) repository
  ansible.builtin.dnf:
    name: epel-release
    state: latest

- name: Enable the CRB (Code Ready Builder) repository
  community.general.dnf_config_manager:
    name: crb
    state: enabled
