- name: Install neovim dependencies
  ansible.builtin.dnf:
    name:
      - wget
      - compat-lua-libs
      - libtermkey
      - libtree-sitter
      - libvterm
      - luajit
      - luajit2.1-luv
      - msgpack
      - unibilium
      - xsel
      - tar
    state: latest

- name: Create share and bin directories for neovim
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: '0755'
  loop:
    - "{{ home }}/.local/share"
    - "{{ home }}/.local/bin"

- name: Download neovim release
  ansible.builtin.get_url:
    url: "{{ neovim_url }}/{{ neovim_version }}/nvim-linux64.tar.gz"
    dest: "{{ home }}/.local/share/"
    checksum: "sha256:{{ neovim_url }}/{{ neovim_version }}/nvim-linux64.tar.gz.sha256sum"
  register: neovim_download

- name: Unarchive neovim release
  ansible.builtin.unarchive:
    src: "{{ home }}/.local/share/nvim-linux64.tar.gz"
    dest: "{{ home }}/.local/share/"
    remote_src: true
  when: neovim_download.changed

- name: Create neovim executable symlink
  ansible.builtin.file:
    src: "{{ home }}/.local/share/nvim-linux64/bin/nvim"
    dest: "{{ home }}/.local/bin/nvim"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: link
  when: neovim_download.changed
