- name: Install XRDP
  ansible.builtin.dnf:
    name:
      - xrdp
    state: latest

- name: Enable the XRDP and XRDP-SESMAN services
  ansible.builtin.systemd_service:
      name: "{{ item }}"
      enabled: true
  loop:
    - xrdp
    - xrdp-sesman

- name: Start the XRDP and XRDP-SESMAN services
  ansible.builtin.systemd_service:
      name: "{{ item }}"
      state: started
  loop:
    - xrdp
    - xrdp-sesman

- name: Start i3 for graphical sessions
  lineinfile:
    path: "{{ home }}/.xsession"
    line: exec i3
    mode: '0755'
    state: present
    create: true
